### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Maverick172** [zihangs/GR_system_AIJ#3]
Exception in thread "main" java.lang.NullPointerException
        at IPC_domains.getProblemsNum(IPC_domains.java:118)
        at IPC_domains.main(IPC_domains.java:50)
Have you encountered this type of issue before?

**Comment by zihangs** [comment]
I need to recall about this, so which command you tried to run?

**Comment by Maverick172** [comment]
Experiments for IPC domains

**Comment by Maverick172** [comment]
I have solved this problem already, but it has created more trouble.

**Comment by Maverick172** [comment]
User
Exception in thread "main" java.lang.NumberFormatException: For input string: "blocks-world"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at IPC_domains.main(IPC_domains.java:29)
The situation is getting more and more complicated.

**Comment by zihangs** [comment]
I guess you are running this command "java -jar gr_ipc.jar ../synthetic_domains/topk/ blocks-world 50 1.5 1.0 1.0". From the error message, it seems like the input parameters are not matching the data format. The place you put "blocks-world" should be some number. I am running perfectly good on my system. Could you please show a screenshot of your command? By the way, what operating system you are using? Linux? MacOS?

**Comment by Maverick172** [comment]
Just like this, and I'm running on an IDE in the Windows system.
![Uploading PM_error.png…]()

**Comment by Maverick172** [comment]
![PM_error](https://github.com/zihangs/GR_system_AIJ/assets/151419733/438ff215-4085-4953-bcae-ebd97ed2ddec)

**Comment by zihangs** [comment]
Did you go into the synthetic_domains/topk/ directory and extract "blocks-world.tar.bz2" to blocks-world/ (extract the tar.bz2 file to a folder)? We need to extract each domain and then run this code.

**Comment by Maverick172** [comment]
I have extracted each domain file under the synthetic_domains/topk/ directory and attempted to run it again. However, it still doesn't work. Below is the new problem I encountered. By the way, the path where the domain files are located is D:\goal_recognition\dataset\synthetic_domains\topk.
![domain file](https://github.com/zihangs/GR_system_AIJ/assets/151419733/50521fe0-fb34-4d25-a7c1-0b87ca22aac2)
![error2](https://github.com/zihangs/GR_system_AIJ/assets/151419733/197be72b-04c9-4be5-81d6-09715e85db4a)

**Comment by zihangs** [comment]
I think that's the difference of running on Linux and windows. On Linux a directory use "/", but windows is "\". Could you please try it on Linux or WSL? Sorry, I didn't consider much about Windows users, I assume people using windows should have a Linux subsystem.
